# 21.12.13

데브캠프 2주 - 1일차  
선형대수  

### 주피터 노트북 설치와 사용

In [4]:
import numpy as np

### Numpy 사용 이유

단순 파이썬 list와 비교해서 속도가 월등히 빠르다.  
-> 내부 자료형을 통일해 쓸데없는 연산을 줄였기 때문.  

# 선형대수

선형대수를 배워봅시다.  

## 선형시스템

일차 방정식을 다른 말로 선형시스템이라고 함  
일차 - 연립일차 등등..  
선형대수의 목표는 어떤 연립일차방정식 문제를 정형적인 방법(가우스 소거법 등)으로 표현하고 해결하는 것.  
**즉 `Ax = b`방식으로 만들어 풀겠다!**

연립 방정식을 행렬식으로 변환하기.  

In [7]:
# 행렬
A = np.array([[3, 1, 1], [1, -2, -1], [1, 1, 1]])

print(A)
print(np.shape(A))

[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [6]:
# 벡터
b = np.array([4, 1, 2])

print(b)
print(np.shape(b))

[4 1 2]
(3,)


In [9]:
# 역행렬 구하기
A_inv = np.linalg.inv(A)

print(A)
print(np.shape(A_inv))


[[ 3  1  1]
 [ 1 -2 -1]
 [ 1  1  1]]
(3, 3)


In [10]:
# Ax = b의 해 x 구하기
x = A_inv @ b

print(x)

[ 1. -1.  2.]


In [15]:
# 검증
b_val = A @ x

print(b_val)

if np.linalg.norm(b - b_val) < 1e-3:
    print("OK")
else:
    print("error")

[4. 1. 2.]
OK


## 가우스 소거법

전방소거법와 후방대입법을 순서대로 진행  

### 전방소거법(Forward elimination)
```py
[*, *, *] [x1]   [*]
[*, *, *] [x2] = [*]
[*, *, *] [x3]   [*]
형태의 식을 

[*, *, *] [x1]   [*]
[0, *, *] [x2] = [*]
[0, 0, *] [x3]   [*]
형태로 바꿔주는 것
```  
먼저 식을 위에서부터 e1, e2, e3라고 한다면  
e2, e3의 x1의 계수를 0으로 만들고,  
e3의 x2계수를 0으로 만들어준다.  
마지막으로 각 식의 첫번째 미지수의 계수를 1로 맞춰준다.  


- 선형시스템을 가장 풀기 쉬운 꼴로 변형해준다.
- 선형시스템의 랭크를 알려준다.
- 선형시스템이 해가 있는지 없는지를 알려준다.

### 후방 대입법  
위에서 만든 식에서 x3부터 차례로 대입하며 찾아나가는것.  

## LU분해
`Ax = b => (LU)x = b => L(Ux)=b => Ly = b`  
A를 L(하삼각행렬)과 U(상삼각행렬)의 곱으로 분해해서 식을 좀 더 쉽게 풀기 위함.  
```py
==========L==========
[*, 0, 0] [y1]   [*]
[*, *, 0] [y2] = [*]
[*, *, *] [y3]   [*]

==========U==========
[*, *, *] [x1]   [y1]
[0, *, *] [x2] = [y2]
[0, 0, *] [x3]   [y3]

A = LU
```  
LU분해는 가우스 소거법의 `forward elimination`을 **행렬로 코드화** 한 것.  
- L: A를 전방소거하는데 쓰인 replacement와 scaling에 대한 EROs를 기록해둔 행렬
- U: A를 전방소거하고 남은 상삼각행렬
- P: A를 전방소거하는데 쓰인 교환에 대한 EROs를 기록해 둔 행렬  
  
---   
- A의 역행렬을 구하는 것 보다 PLU분해를 이용하는것이 안정적이다.  
- A는 고정되어있고, b가 자주 업데이트되는 경우 A를 PLU로 분해해둔다면, b가 변하더라도 실시간으로 x를 구할 수 있다.