# 21.12.20

### 표본분포  
표본조사를 통해 파악하고자 하는 정보: 모수  
(모평균, 모분산, 모비율 등)  
통계량: 표본평균이나 표본 분산과 같은 표본의 특성값  

표본평균: 모평균을 알아내는데 쓰임  
표본평균은 표본을 어떻게 뽑느냐에 따라서 달라지며,  
모집단이 정규분포인경우 표본평균을 모아놓고 보면 정규분포를 따른다.  
표본이 충분히 많으면 표본평균, 표본분산은 모평균, 모분산을 따른다 -> 중심극한정리  

### 추정
모평균을 추정함  
점추정: 표본평균이 점추정이 됨  
- 구간추정
    - 내가 만든 구간 안에 모평균이 있을것이다.  
    - 시그마(모표준편차)를 알때 공식을 사용할 수 있으나, 잘 안씀
    - 표본의 크기가 커서 중심극한 정리를 사용할 수 있을때, 표본평균을 계산하고, 표본표준편차를 사용해서 구간을 구함.  

모비율의 추정  
모집단에서 사건의 확률을 추정하는것.  
점추정: 확률변수 X -> n개의 표본에서 특정 속성을 갖는 표본의 개수  
구간추정: n이 충분히 클때 사용, 확률변수 X를 표준화해서 Z로 만듦.  


## Numpy

### Numpy로 연산하기
벡터와 스칼라 연산.  
벡터의 각 원소에 대해서 연산을 진행  

In [1]:
import numpy as np

x = np.array([1,2,3])
c = 5

print(f"더하기 : {x+c}")
print(f"빼기 : {x-c}")
print(f"곱하기 : {x*c}")
print(f"나누기 : {x/c}")

더하기 : [6 7 8]
빼기 : [-4 -3 -2]
곱하기 : [ 5 10 15]
나누기 : [0.2 0.4 0.6]


In [3]:
# 벡터와 벡터 연산
# 벡터의 같은 인덱스끼리 연산 진행

y = np.array([1, 3, 5])
z = np.array([2, 9, 20])

print(f"더하기 : {y+z}")
print(f"빼기 : {y-z}")
print(f"곱하기 : {y*z}")
print(f"나누기 : {y/z}")

더하기 : [ 3 12 25]
빼기 : [ -1  -6 -15]
곱하기 : [  2  27 100]
나누기 : [0.5        0.33333333 0.25      ]


In [8]:
# Array indexing
# index를 기준으로 콤마로 구분 [a][b] => [a, b]
W = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])

print(W[2, 3])
print(W[0:2, 1:3])

12
[[2 3]
 [6 7]]


### Numpy의 Broadcasting
1. *M x N, M x 1*  
2. *M x N, N x 1*
3. *M x 1, 1 x N*
위 경우 모두 연산이 가능하도록 Duplicate해서 연산이 된다.  
기본적으로 같은 타입의 Data에만 연산이 가능하나, 피연산자가 변환 가능하다면 변환후 연산 됨.  

In [13]:
# M by N, M by 1
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([0, 1, 0])

print(a + x)
x = x[:, None]
print(a + x)

# M by N, 1 by N
y = np.array([0, 1, -1])
print(a * y)

# M by 1, 1 by N
t = np.array([1, 2, 3])
t = t[:, None]
u = np.array([2, 0, -2])

print(t + u)

[[1 3 3]
 [4 6 6]
 [7 9 9]]
[[1 2 3]
 [5 6 7]
 [7 8 9]]
[[ 0  2 -3]
 [ 0  5 -6]
 [ 0  8 -9]]
[[ 3  1 -1]
 [ 4  2  0]
 [ 5  3  1]]


## Numpy로 선형대수

In [17]:
# 원소가 모두 0인 벡터(행렬)
# 크기를 전달
print(np.zeros(3))
print(np.zeros((3,3)))

# 원소가 모두 1인 ~~
print(np.ones(3))
print(np.ones((3,3)))

[0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [20]:
# 대각행렬 diagonal matrix
# 원소를 전달
print(np.diag((2, 4)))
print(np.diag((1,3,5)))


[[2 0]
 [0 4]]
[[1 0 0]
 [0 3 0]
 [0 0 5]]


In [21]:
# 항등행렬 identity
# 크기를 전달
print(np.eye(2, dtype=int))

[[1 0]
 [0 1]]


In [22]:
# 행렬곱
# np.dot() or @ 
# 위의 둘은 3차원 이상에서는 다르게 연산된다.  

mat1 = np.array([[1, 4], [2, 3]])
mat2 = np.array([[7, 9], [0, 6]])

print(mat1.dot(mat2))
print(mat1 @ mat2)

[[ 7 33]
 [14 36]]
[[ 7 33]
 [14 36]]


In [23]:
# trace
# main diagonal의 합

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.trace(a))

15


In [ ]:
# 행렬식
# 행렬을 대표하는 값들 중 하나

In [9]:

class myRange:
    def __init__(self, start_num, end_num):
        self.start_num = start_num
        self.end_num = end_num
    
    def __iter__(self):
        current_num = self.start_num
        while current_num < self.end_num:
            yield current_num
            current_num += 1

r1 = myRange(4, 9)
list(r1)

[4, 5, 6, 7, 8]

In [13]:
class myRange:
    def __init__(self, start_num: int, end_num: int):
        self.start_num = start_num
        self.end_num = end_num
        self._range = self._create_range()
    
    def _create_range(self):
        nums = []
        cur_num = self.start_num
        while cur_num < self.end_num:
            nums.append(cur_num)
            cur_num += 1
        return nums
    
    def __getitem__(self, num_ind: int):
        return self._range[num_ind]
    
    def __len__(self):
        return len(self._range)

r1 = myRange(4, 9)
print(list(r1))
print(r1[4])
print(len(r1))

[4, 5, 6, 7, 8]
8
5
