### Why Pytorch?
- Numpy를 대체하면서 GPU를 이용한 연산이 필요한 경우
- 최대한의 유연성과 속도를 제공하는 딥러닝 연구 플랫폼이 필요한 경우

#### Getting Started
Tensor는 Numpy의 ndarray와 유사하며, 추가로 GPU를 사용한 연산 가속도 가능하다.

In [1]:

from __future__ import print_function
import torch

torch.__version__

'1.10.2+cu113'

In [2]:
# 초기화 되지 않은 5x3행렬
x = torch.empty(5,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
# 무작위로 초기화된 행렬
x = torch.randn(5,3) # normal distribution
print(x)
x = torch.rand(5,3) # 0 ~ 1
print(x)

tensor([[ 0.0226,  2.3274,  0.1594],
        [ 0.8384, -1.1330, -0.4682],
        [-0.5986,  0.9155, -1.7236],
        [ 1.3008, -0.5764,  1.7510],
        [-0.0681,  0.0127, -0.8202]])
tensor([[0.0847, 0.8109, 0.0557],
        [0.9166, 0.6709, 0.5330],
        [0.0155, 0.5705, 0.4576],
        [0.2379, 0.4494, 0.9601],
        [0.9400, 0.6339, 0.8144]])


In [4]:
# dtype이 long이고 0으로 채워진 행렬
x = torch.zeros(5,3, dtype=torch.long)
print(x)

# 1로 채워진~
x = torch.ones(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [5]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.6001, -0.3352,  1.0847],
        [-0.5537,  2.2189, -0.7711],
        [ 0.4132,  0.0691,  0.5289],
        [ 2.5131, -0.6213,  0.5832],
        [ 0.3596, -0.1203, -1.0008]])


In [7]:
print(x.size())
print(x.shape)

torch.Size([5, 3])
torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x+y)
# 각 값끼리 더한다. 

tensor([[-1.6001, -0.3352,  1.0847],
        [-0.5537,  2.2189, -0.7711],
        [ 0.4132,  0.0691,  0.5289],
        [ 2.5131, -0.6213,  0.5832],
        [ 0.3596, -0.1203, -1.0008]])
tensor([[0.1387, 0.7538, 0.3579],
        [0.2308, 0.0877, 0.2151],
        [0.5202, 0.1004, 0.3449],
        [0.2818, 0.2100, 0.0215],
        [0.0340, 0.8750, 0.9507]])
tensor([[-1.4614,  0.4186,  1.4426],
        [-0.3228,  2.3066, -0.5560],
        [ 0.9334,  0.1694,  0.8738],
        [ 2.7949, -0.4113,  0.6047],
        [ 0.3937,  0.7546, -0.0500]])


In [ ]:
print(torch.add(x, y))

tensor([[ 1.6635,  1.0792, -0.0352],
        [ 1.2603,  1.1204, -0.0444],
        [ 0.8993,  1.7855,  0.7441],
        [ 1.4508,  2.2650,  1.8526],
        [ 0.1410,  1.2628,  0.5240]])


In [ ]:
result = torch.empty(5,3)

torch.add(x, y, out=result)
print(result)

tensor([[ 1.6635,  1.0792, -0.0352],
        [ 1.2603,  1.1204, -0.0444],
        [ 0.8993,  1.7855,  0.7441],
        [ 1.4508,  2.2650,  1.8526],
        [ 0.1410,  1.2628,  0.5240]])


In [ ]:
# inplace방식 -> _를 접미로 가진다.
print(y)
y.add_(x)
print(y)

tensor([[0.5628, 0.6460, 0.1620],
        [0.8988, 0.6710, 0.1090],
        [0.9301, 0.9590, 0.2452],
        [0.8518, 0.4961, 0.2436],
        [0.5622, 0.5054, 0.0365]])
tensor([[ 1.6635,  1.0792, -0.0352],
        [ 1.2603,  1.1204, -0.0444],
        [ 0.8993,  1.7855,  0.7441],
        [ 1.4508,  2.2650,  1.8526],
        [ 0.1410,  1.2628,  0.5240]])


In [ ]:
print(x)
print(x[:, 1])

tensor([[ 1.1007,  0.4332, -0.1973],
        [ 0.3614,  0.4494, -0.1534],
        [-0.0308,  0.8265,  0.4989],
        [ 0.5990,  1.7689,  1.6089],
        [-0.4212,  0.7574,  0.4876]])
tensor([0.4332, 0.4494, 0.8265, 1.7689, 0.7574])


In [ ]:
x = torch.randn(4, 4)
print(x)

# reshape
y = x.view(16)
z = y.view(-1, 2)
print(y)
print(z)


tensor([[ 0.4854,  1.4263, -1.5820,  0.7576],
        [-0.0401,  2.0656,  0.0208,  1.3769],
        [ 0.4292, -0.9824, -1.0087,  0.5948],
        [ 0.1989, -0.2519, -0.3371,  0.3230]])
tensor([ 0.4854,  1.4263, -1.5820,  0.7576, -0.0401,  2.0656,  0.0208,  1.3769,
         0.4292, -0.9824, -1.0087,  0.5948,  0.1989, -0.2519, -0.3371,  0.3230])
tensor([[ 0.4854,  1.4263],
        [-1.5820,  0.7576],
        [-0.0401,  2.0656],
        [ 0.0208,  1.3769],
        [ 0.4292, -0.9824],
        [-1.0087,  0.5948],
        [ 0.1989, -0.2519],
        [-0.3371,  0.3230]])


In [ ]:
# tensor에 값이 하나라면 .item()으로 숫자값 반환, 값이 여러개면 오류

x = torch.randn(1)
print(x)
print(type(x), type(x.item()))
print(x.item())

tensor([0.8982])
<class 'torch.Tensor'> <class 'float'>
0.898156464099884


In [ ]:
# tenssor to numpy
# cpu상의 tensor와 numpy는 저장공간을 공유하기 때문에, 하나를 변경하면 다른 것도 변경됨
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)

a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [ ]:
temp = a.clone()
temp_numpy = temp.numpy()

a.add_(1)
print(a)
print(temp_numpy)
print(temp)

tensor([3., 3., 3., 3., 3.])
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.])


In [ ]:
# numpy to torch
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### CUDA Tensors

In [ ]:
x = torch.rand(4,4)
if torch.cuda.is_available():
    device = "cuda:0"
    y = torch.ones_like(x, device= device)
    print(y)

    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

C:\Users\leejoon-byeong\anaconda3\envs\stdata\lib\site-packages\torch\cuda\__init__.py:106: UserWarning: 
NVIDIA GeForce RTX 3070 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the NVIDIA GeForce RTX 3070 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))


In [15]:
x = x.cuda()

NameError: name 'x' is not defined

#### Tensorflow

In [16]:
import tensorflow as tf
print(tf.__version__)

ModuleNotFoundError: No module named 'tensorflow'

In [ ]:
my_variable = tf.Variable(tf.zeros([1, 2, 3]))
my_variable

In [ ]:
v = tf.Variable(0.0)
print(v)

w = v + 1
print(w)

In [ ]:
a= tf.Variable(0.0)
a.assign_add(1)
a.read_value()

In [ ]:
mammal = tf.Variable("코끼리", tf.string)
ignition = tf.Variable(451, tf.int16)
floating = tf.Variable(3.1412345, tf.float64)
its_complicated = tf.Variable(12.3 - 4.85j, tf.complex64)

print(mammal)
print(ignition)
print(floating)
print(its_complicated)

In [ ]:
# 랭크 1 -> 벡터
mystr = tf.Variable(['안녕하세요'], tf.string)
cool_numbers = tf.Variable([3.14, 2.71], tf.float32)

print(tf.rank(mystr))
print(tf.rank(cool_numbers))

In [ ]:
# 랭크2 -> 열과 행
mymat = tf.Variable([[7, 4, 5], [11, 12, 12], [12, 14, 16]], tf.int16)
print(tf.rank(mymat))

In [ ]:
# 랭크 4 -> 이미지?
my_image = tf.zeros([10, 299, 299, 3]) # 배치x높이x너비x색상

print(tf.rank(my_image))